import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/navbar";
import { Toaster } from "react-hot-toast";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${inter.variable}  bg-white text-slate-600 antialiased selection:bg-emerald-100 selection:text-emerald-900`}
      >
        {/* <Navbar/> */}
        {children}
        <Toaster />
      </body>
    </html>
  );
}
